### ISSUE TITLE
Certificate/Private Key

### ISSUE THREAD

**Issue by metamarcdw** [takinbo/eps-docker#1]
Are we supposed to use the given Certificate/Private Key, or are we supposed to create our own? Seems like a security issue if its the former.

**Comment by takinbo** [comment]
If you're connecting to a locally installed version of eps, it's not much of a security issue and yes you can always replace the certificate and private key with those created by yourself. This key pair is added for convenience and only affects the communications layer. Please note that electrum caches certificates for servers that you connect to so if you intend to change your key pair, you should do that before connecting or at most, delete the cached certificate or you wouldn't be able to connect.

**Comment by takinbo** [comment]
closing since there hasn't been any further discussion on this.
